import TarotCore

/// Holds all the necessary data returned after a successful card drawing and synthesis process.
public struct ReadingResult {
    
    /// The specific spread configuration that was used for this reading (e.g., Celtic Cross).
    public let spread: Spread 
    
    /// The list of cards drawn, each linked to its position and orientation.
    public let drawnCards: [DrawnCard] 
    
    /// The high-level summary generated by the synthesizer (used for quick display).
    public let synthesisSummary: String 
    
    // MARK: Initializers
    
    /// Initializes a ReadingResult with all components of the reading.
    public init(spread: Spread, drawnCards: [DrawnCard], synthesisSummary: String) {
        self.spread = spread
        self.drawnCards = drawnCards
        self.synthesisSummary = synthesisSummary
    }
}
